import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
const root = document.querySelector('.os-studio');
if (root) init(root);
function init(root) {
 const chapters=JSON.parse(root.dataset.chapters), canvas=root.querySelector('canvas'), viewport=canvas.parentElement;
 const $=s=>root.querySelector(s), reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let renderer,scene,camera,controls,world,current=0,state={},busy=false,tweens=[],visible=true,dirty=true;
 const pickables=[], objects={}, resources=[];
 const colors={blue:0x6378e6,purple:0x9a8be5,mint:0x88c9b3,orange:0xe7b97e,pink:0xd994ae,ink:0x40516b,ground:0xe5eaf2};
 try{
 renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,150);camera.position.set(15,15,18);
 controls=new OrbitControls(camera,canvas);controls.target.set(0,0,0);controls.enableDamping=true;controls.addEventListener('change',()=>{dirty=true;});controls.enablePan=false;controls.minDistance=11;controls.maxDistance=65;controls.maxPolarAngle=Math.PI*.43;
 scene.add(new THREE.HemisphereLight(0xffffff,0xa1abc8,1.35));const sun=new THREE.DirectionalLight(0xffffff,1.8);sun.position.set(-8,18,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-15;sun.shadow.camera.right=15;sun.shadow.camera.top=15;sun.shadow.camera.bottom=-15;sun.shadow.bias=-.001;scene.add(sun);
 new ResizeObserver(()=>{const {width,height}=viewport.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();dirty=true;if(width<600){camera.position.set(15,15,18).multiplyScalar(Math.max(1,1.15/camera.aspect));}}).observe(viewport);
 new IntersectionObserver(e=>{visible=e[0].isIntersecting;}).observe(viewport);
 renderer.setAnimationLoop(time=>{if(document.hidden||(!visible&&!busy))return;for(const t of [...tweens]){const f=Math.min(1,(time-t.start)/t.duration),p=1-(1-f)**3;t.update(p);dirty=true;if(f===1){tweens.splice(tweens.indexOf(t),1);t.done?.();}}controls.update();if(dirty||busy||tweens.length){renderer.render(scene,camera);dirty=false;}});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('.fallback').hidden=false;});
 }catch(e){renderer=null;$('.fallback').hidden=false;}
 function mat(color){const m=new THREE.MeshStandardMaterial({color,roughness:.72});resources.push(m);return m;}
 function box(parent,x,y,z,w,h,d,color,rotation=0){const g=new THREE.BoxGeometry(w,h,d);resources.push(g);const m=new THREE.Mesh(g,mat(color));m.position.set(x,y+h/2,z);m.rotation.y=rotation;m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function cylinder(parent,x,y,z,r,h,color){const g=new THREE.CylinderGeometry(r,r,h,24);resources.push(g);const mesh=new THREE.Mesh(g,mat(color));mesh.position.set(x,y+h/2,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 function text(parent,label,x,y,z,size=.55,color='#586889'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font='600 64px system-ui';const fontSize=Math.min(64,64*480/Math.max(480,ctx.measureText(label).width));ctx.font=`600 ${fontSize}px system-ui`;ctx.textAlign='center';ctx.fillText(label,256,78);const t=new THREE.CanvasTexture(c);resources.push(t);const m=new THREE.SpriteMaterial({map:t,depthTest:false});resources.push(m);const s=new THREE.Sprite(m);s.position.set(x,y,z);s.scale.set(size*6,size*1.5,1);parent.add(s);return s;}
 function selectable(group,name,desc){group.userData={name,desc};const b=document.createElement('button');b.textContent=name;b.onclick=()=>select(name,desc);$('.object-list').append(b);group.traverse(o=>{if(o.isMesh){o.userData.owner=group;pickables.push(o);}});}
 function building(name,x,z,w=2.7,d=2.5,h=1.6,color=colors.blue){const g=new THREE.Group();g.position.set(x,0,z);world.add(g);box(g,0,0,0,w+.25,.15,d+.25,0xd1d9e8);box(g,0,.15,0,w,h,d,color);box(g,0,h+.15,0,w+.22,.22,d+.22,color);box(g,0,.15,d/2+.03,.8,1.05,.07,0xe9edf7);for(let j=-1;j<=1;j+=2)box(g,j*w*.3,.75,d/2+.04,.38,.45,.05,0xc3d3f6);text(g,name,0,h+.95,0,.45);return g;}
 function road(x,z,w,d){box(world,x,.025,z,w,.03,d,0xcdd7e5);if(w>d){for(let a=-w/2+.5;a<w/2;a+=.8)box(world,x+a,.07,z,.32,.005,.05,0xf5f7fb);}else{for(let a=-d/2+.5;a<d/2;a+=.8)box(world,x,.07,z+a,.05,.005,.32,0xf5f7fb);}}
 function tree(x,z){cylinder(world,x,.1,z,.055,.5,0xb8a992);const geo=new THREE.SphereGeometry(.35,12,10);resources.push(geo);const m=new THREE.Mesh(geo,mat(0xa5ccb2));m.position.set(x,.88,z);m.scale.y=1.3;m.castShadow=true;world.add(m);}
 function bot(name,x,z,color=colors.blue){const g=new THREE.Group();g.position.set(x,.13,z);world.add(g);box(g,0,.1,0,.65,.3,.95,color);box(g,0,.4,-.1,.5,.37,.45,0xfafcff);box(g,0,.49,.135,.36,.17,.025,0x53657c);for(const a of [-.34,.34])for(const b of [-.27,.27]){const wheel=cylinder(g,a,0,b,.115,.07,0x44516a);wheel.rotation.z=Math.PI/2;}box(g,0,.78,-.13,.18,.18,.18,color);text(g,name,0,1.4,0,.34);selectable(g,name,'Process kimliği hareket boyunca korunur. Konumu bu deneyde durumunu veya kaynak erişimini temsil eder.');return g;}
 function token(x,z,color=colors.orange){return box(world,x,.13,z,.35,.35,.35,color);}
 function rack(name,x,z,value=10,color=colors.purple){const g=new THREE.Group();g.position.set(x,0,z);world.add(g);box(g,0,0,0,2.1,.14,1.8,0xd2dbea);for(let i=0;i<4;i++){box(g,0,.2+i*.39,0,1.8,.3,1.35,color);box(g,.65,.26+i*.39,.685,.13,.1,.03,0xd5f7ed);}text(g,name,0,2.3,0,.45);const label=text(g,`x = ${value}`,0,1.05,1.1,.35,'#fff');selectable(g,name,'Code, data, heap ve stack kavramsal alanları. Fiziksel sayfa paylaşımı sıradan yazılabilir değişkenleri ortak yapmaz.');return {group:g,label};}
 function tween(update,done,duration=950){if(!renderer||reduced.matches){update(1);done?.();return;}tweens.push({start:performance.now(),duration,update,done});}
 function move(obj,x,z,done){if(!obj){done?.();return;}const start=obj.position.clone();if(obj.isGroup&&Math.hypot(x-start.x,z-start.z)>.01)obj.rotation.y=Math.atan2(x-start.x,z-start.z);tween(p=>{obj.position.x=start.x+(x-start.x)*p;obj.position.z=start.z+(z-start.z)*p;},done);}
 function event(message,cpu='—',resource='—'){ dirty=true;$('#event-text').textContent=message;$('#cpu-metric').textContent=cpu;$('#resource-metric').textContent=resource;}
 function note(text){$('#insight-text').textContent=text;}
 function lock(action){if(busy)return;busy=true;action(()=>{busy=false;});}
 function cleanup(){dirty=true;tweens=[];busy=false;pickables.length=0;$('.object-list').replaceChildren();resources.forEach(r=>r.dispose());resources.length=0;if(world)scene.remove(world);for(const k of Object.keys(objects))delete objects[k];world=new THREE.Group();scene?.add(world);}
 function floor(){box(world,0,-.3,0,17,.3,12,0xe4eaf3);box(world,0,-.4,0,17.2,.1,12.2,0xd4deee);road(0,2.4,15,1.5);road(0,-1,1.4,7);for(const x of [-6,6]){cylinder(world,x,.1,.9,.04,1.6,colors.ink);box(world,x,1.7,.9,.35,.08,.35,0xf8f3d7);box(world,x,-.01,4.8,1.1,.12,.42,0xc3cddd);}for(const [x,z] of [[-7,-4],[7,-4],[-7,4],[7,4],[6,-4],[-6,-4]])tree(x,z);}
 function cpu(x=0,z=-2){const c=building('CPU',x,z,2.8,2.6,1.7,colors.blue);box(c,0,1.97,0,1.15,.12,1.1,0x384b9a);for(let i=-.6;i<=.6;i+=.3){box(c,i,1.9,.78,.12,.16,.38,0xbdc9ef);box(c,i,1.9,-.78,.12,.16,.38,0xbdc9ef);}selectable(c,'CPU · yürütme merkezi','Running görev burada CPU kullanır. Ready görev seçilmeyi bekler; waiting görev eksik olayı bekler.');return c;}
 function pad(name,x,z,color){box(world,x,0,z,3.5,.08,2.4,color);text(world,name,x,.7,z-1.15,.4);}
 function actionButtons(items){$('.actions').replaceChildren();for(const [label,fn] of items){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(!busy)fn();};$('.actions').append(b);}const reset=document.createElement('button');reset.textContent='Deneyi sıfırla';reset.onclick=()=>load(current);$('.actions').append(reset);}
 function labelChange(rack,name,x,z,v){rack.label.removeFromParent();rack.label=text(rack.group,v,0,1.05,1.1,.35,'#fff');}
 const scenes=[
 ()=>{floor();cpu();objects.memory=rack('MEMORY',-4,-2);const io=building('I/O',4,-2,2.3,2.1,1.1,colors.mint);selectable(io,'I/O · harici olay','Disk, ağ ve klavye gibi olayların tamamlanması CPU seçimiyle aynı şey değildir.');objects.p=bot('P · 101',-5,2.4);pad('READY QUEUE',-4,3.7,0xdbe1fa);pad('WAITING',4,3.7,0xe1e9e5);event('Bir komutu başlat; süreç kaynaklara erişsin.','Boş','Process · memory · I/O');note('Sahnedeki yapılar bir benzetme: kernel kaynakları yönetir; süreçlerin durumunu ve adres alanlarını birbirinden ayırır.');actionButtons([['Komutu başlat',()=>lock(done=>{event('P hazır → scheduler seçiyor','P seçiliyor','PID 101');move(objects.p,0,2.4,()=>move(objects.p,0,-.2,()=>{event('P CPU’da çalışıyor.','P · running','PID 101');done();}));})],['Belleği incele',()=>select('MEMORY','Process’in code, data, heap ve stack alanları sanal adres uzayındadır. Register ve PC yürütme context’idir.')],['Dönem planı',()=>{event('1–6, 8–10: ders · 7: ara sınav · 11–14: İngilizce makale sunumu','Ara %30 · Final %40','Sunum %15 · Ödev %15');note('Final sorularının yarısı sunumlardan. Yaklaşık iki haftalık Ubuntu ödevleri; AI desteğine izin var. Ayrıntılı yönergeler ayrıca açıklanacak.');}]]);},
 ()=>{floor();const user=building('USER SPACE',-4,-1,3.1,2.9,1.1,colors.mint);const kernel=building('KERNEL',4,-1,3.1,2.9,2,colors.blue);selectable(user,'User mode','Kısıtlı CPU ayrıcalıkları. Root kullanıcı kimliğidir; CPU privilege mode’u değildir.');selectable(kernel,'Kernel mode','System call, exception ve interrupt kontrollü kernel girişi oluşturabilir.');road(0,2.4,12,1.5);objects.p=bot('P · PID 101',-4,2.4);box(world,0,.1,2.4,.16,1.1,1.7,colors.orange);text(world,'KONTROLLÜ GİRİŞ',0,1.8,2.4,.4);event('P user mode’da; PID 101.','P · user','Privilege boundary');note('Bu deney aynı P’nin yetki modu değişimini gösterir. Kernel’e giriş, başka process’in çalışması demek değildir.');actionButtons([['System call',()=>lock(done=>{move(objects.p,4,2.4,()=>{event('P kernel’de hizmet aldı → aynı P geri dönüyor','P · kernel','PID hâlâ 101');move(objects.p,-4,2.4,()=>{event('P user mode’a döndü; görev değişimi yok.','P · user','PID 101');done();});});})],['Page fault',()=>{event('Exception: geçerli talimat page fault oluşturdu.','P → kernel','Eksik memory page');note('Exception kernel giriş nedenidir. Hizmet bloklarsa başka görev seçilebilir; bu sahne otomatik task switch varsaymaz.');}],['Device interrupt',()=>{event('I/O cihazı tamamlanmayı bildirdi; kernel olayı işler.','Kernel entry','Task switch zorunlu değil');}],['Kütüphane çağrısı',()=>{event('User-space hesap: kernel girişine ihtiyaç yok.','P · user','Fonksiyon ≠ syscall');note('printf tamponu birden çok çağrıyı tek write ile birleştirebilir. API adı ile tracer’daki syscall adı farklı olabilir.');}]]);},
 ()=>{floor();objects.a=rack('P · PID 101',-4,-1,10,colors.blue);objects.b=rack('Q · PID 202',4,-1,10,colors.purple);building('EXECUTABLE',0,-3.5,2,1.3,.7,colors.mint);text(world,'AYRI ADRES ALANLARI',0,1,3,.55);state={a:10,b:10,alive:true};event('Aynı executable, iki process: P.x=10 · Q.x=10','Bağımsız context','Ayrı yazılabilir bellek');note('Pointer adres değeridir; ömrü uzatmaz veya başka process’te ortak bellek yaratmaz. PCB tüm belleğin kopyası değil context ve kaynak referanslarıdır.');actionButtons([['P: x = 20',()=>{if(!state.alive)return event('P sonlandı; yazma yapamaz.','Q','Önce deneyi sıfırla');state.a=20;labelChange(objects.a,'P',-4,-1,'P.x = 20');event('P yazdı. Q.x hâlâ 10.','P','Process isolation');}],['P’yi sonlandır',()=>{state.alive=false;objects.a.group.visible=false;event('P sonlandı. Q ayrı adres alanında varlığını sürdürüyor.','Q etkilenmedi','Harici ortak bağımlılıklar olabilir');}],['Stack / heap',()=>select('Bellek ve ömür','Local nesne scope boyunca; heap nesnesi serbest bırakılana kadar dil kurallarına göre yaşar. PC/register ayrı context’tir. Gerçek mappings ve büyüme yönleri sisteme göre değişir.')]]);},
 ()=>{floor();cpu(0,-2.8);pad('READY QUEUE',-4,2.4,0xdce1fb);pad('I/O WAIT',4,2.4,0xd9e8df);objects.a=bot('Process A',-4,2.4,colors.blue);objects.b=bot('Process B',-5,3.1,colors.purple);state={a:'ready',b:'ready',cpu:null};event('A ve B ready; CPU boş.','Boş','Ready ≠ waiting');note('I/O tamamlanması A’yı ready yapar. B o sırada çalışıyorsa, A’nın hemen CPU’ya geçtiğini varsayma.');actionButtons([['Scheduler: A’yı seç',()=>{if(state.a!=='ready'||state.cpu)return event('A ready olmalı ve bu basit deneyde CPU boş olmalı.',state.cpu||'Boş','Scheduler');lock(done=>move(objects.a,0,-.6,()=>{state.a='running';state.cpu='A';event('A ready → running','A','CPU sahibi A');done();}));}],['A: disk oku',()=>{if(state.cpu!=='A')return event('Önce A’yı CPU’da çalıştır.','Boş / B','A running değil');lock(done=>move(objects.a,4,2.4,()=>{state.a='waiting';state.cpu=null;event('A disk verisi bekliyor; B seçilebilir.','Boş','A waiting');done();}));}],['Scheduler: B’yi seç',()=>{if(state.cpu||state.b!=='ready')return event('CPU dolu veya B ready değil.',state.cpu||'Boş','Scheduler');lock(done=>move(objects.b,0,-.6,()=>{state.b='running';state.cpu='B';event('B çalışıyor; A’nın I/O’su ayrı ilerler.','B','A '+state.a);done();}));}],['A: I/O tamamlandı',()=>{if(state.a!=='waiting')return event('A henüz I/O beklemiyor.',state.cpu||'Boş','Önce disk oku');lock(done=>move(objects.a,-4,2.4,()=>{state.a='ready';event('A waiting → ready. CPU hâlâ '+(state.cpu||'boş')+'.',state.cpu||'Boş','A ready');done();}));}],['Time slice bitti',()=>{if(!state.cpu)return;const name=state.cpu;lock(done=>move(name==='A'?objects.a:objects.b,-4,name==='A'?2.4:3.1,()=>{state[name.toLowerCase()]='ready';state.cpu=null;event(name+' running → ready.','Boş','Time slice');done();}));}]]);},
 ()=>{floor();cpu();objects.p=rack('P CONTEXT',-4,-1,10,colors.mint);objects.q=rack('Q CONTEXT',4,-1,20,colors.purple);objects.reg=token(0,-.3,colors.blue);state.owner='P';text(world,'PC + REGISTERS',0,1.2,-.2,.4);event('CPU: P · PC=24 · R=7','P','Context kayıtları');note('Yürütme bağlamı saklanır. Tüm bellek PCB’ye kopyalanmaz; farklı mappings seçilebilir. Cache/translation etkileri geçiş maliyetine eklenebilir.');actionButtons([['P → Q context switch',()=>{if(state.owner==='Q')return event('Q zaten CPU’da.','Q','Önce Q → P seç');lock(done=>{event('P: PC=24, R=7 saklanıyor.','Kernel','Save P');move(objects.reg,-4,-1,()=>{objects.reg.position.set(4,.305,-1);objects.reg.material.color.set(colors.purple);move(objects.reg,0,-.3,()=>{state.owner='Q';event('Q kaldığı yerden: PC=80, R=3','Q','Restore Q · mappings Q');done();});});});}],['Q → P geri yükle',()=>{if(state.owner==='P')return event('P zaten CPU’da.','P','Önce P → Q seç');lock(done=>move(objects.reg,4,-1,()=>{objects.reg.position.set(-4,.305,-1);objects.reg.material.color.set(colors.blue);move(objects.reg,0,-.3,()=>{state.owner='P';event('P tekrar PC=24, R=7 ile devam eder.','P','Context restore');done();});}));}],['Hemen biten syscall',()=>{event(state.owner+' kernel’e girdi ve aynı görev geri döndü.',state.owner,'Task switch yok');}]]);},
 ()=>{floor();objects.parent=bot('Parent · 100',-4,2.4,colors.blue);objects.mem=rack('P · x=10',-4,-1,10,colors.blue);state={forked:false,exec:false};event('Bir parent: PID 100, x=10','Parent','Tek process');note('fork PID oluşturur; exec aynı PID’nin program image’ini değiştirir; wait sonlanma status’unu toplar.');actionButtons([['fork()',()=>{if(state.forked)return;state.forked=true;objects.child=bot('Child · 101',-4,2.4,colors.purple);lock(done=>move(objects.child,4,2.4,()=>{objects.cm=rack('CHILD · x=10',4,-1,10,colors.purple);event('Parent return=101 · child return=0. Çalışma sırası garanti değil.','İki process','COW · ayrı mantıksal alan');done();}));}],['Child: x = 20',()=>{if(!state.forked||state.exec)return event('Önce fork; bu değişken exec öncesi image’e ait.','—','Geçerli child gerekli');labelChange(objects.cm,'child',4,-1,'Child.x = 20');event('Child private copy’ye yazdı. Parent.x = 10.','Child','Copy-on-write');}],['exec /bin/echo',()=>{if(!state.forked)return event('Önce fork yap.','Parent','Child yok');state.exec=true;objects.child.children.filter(o=>o.isMesh&&o.material.color).forEach(o=>o.material.color.set(colors.mint));labelChange(objects.cm,'child',4,-1,'Yeni image: echo');event('PID 101 aynı. Code / data / stack yeni image.','Child · 101','FD close-on-exec değilse kalabilir');}],['exec hata yolu',()=>{if(!state.forked)return;event('Olmayan executable: exec döndü; child _exit(127).','Child sonlandı','Parent wait ile 127 toplar');note('127 örneğin convention’ıdır. Tam örnek fork hatasını, EINTR retry ve WIFEXITED/WEXITSTATUS kontrolünü içerir.');}]]);},
 ()=>{floor();objects.parent=building('PARENT',-4,-2,2.5,2,1.3,colors.blue);objects.child=bot('Child · 101',3,2.4,colors.purple);state={ended:false,reaped:false};event('Child canlı; parent başka iş yapabilir.','Child','PID 101');note('Zombie, programı çalışmayan ama status kaydı kalan sonlanmış process’tir. Parent’ın önce sonlanması farklı bir durumdur.');actionButtons([['Child: exit(0)',()=>{if(state.ended)return;state.ended=true;objects.child.visible=false;objects.record=rack('EXIT STATUS · 0',3,2.4,0,colors.orange);event('Child artık yürütülmüyor. Status kaydı kaldı: zombie.','Child çalışmıyor','Kernel kaydı');}],['Parent: waitpid',()=>{if(!state.ended)return event('Child henüz bitmedi: waitpid bloklayabilir.','Parent waiting','Sonlanmayı bekle');if(state.reaped)return;state.reaped=true;objects.record.group.visible=false;event('Status 0 toplandı; zombie kaydı temizlendi.','Parent','Reaped');}],['Ubuntu gözlemi',()=>select('ps snapshot','sleep 20 &; demo_pid=$!; ps -o pid,ppid,stat,comm -p "$demo_pid"; wait "$demo_pid". Linux R ready veya running olabilir. Bu sahnedeki PID’ler yalnız örnektir.')]]);},
 ()=>{floor();box(world,0,.1,0,9,.15,5,0xdddff3);objects.shared=rack('SHARED HEAP',0,-2,7,colors.purple);objects.t1=bot('T1 · stack 1',-3,1.4,colors.blue);objects.t2=bot('T2 · stack 2',3,1.4,colors.pink);state={cores:1};text(world,'TEK PROCESS · ORTAK ADRES ALANI',0,3,-3,.6);event('İki thread: ayrı PC/register/stack; aynı adres alanı.','1 core','Ortak heap + files');note('Ayrı stack’ler memory protection sınırı değildir. Pointer diğer thread’in canlı stack nesnesine erişebilir; hatalı thread ortak belleği bozabilir.');actionButtons([['1 core: interleave',()=>lock(done=>{move(objects.t1,0,1.4,()=>{event('Önce T1, sonra T2: örtüşen ilerleme.','T1 → T2','Concurrency');move(objects.t1,-3,1.4,()=>move(objects.t2,0,1.4,()=>{done();}));});})],['2 core: paralel',()=>lock(done=>{let n=0;const finish=()=>{if(++n===2){event('T1 ve T2 farklı core’larda aynı anda yürüyebilir.','Core 1 + Core 2','Parallelism');done();}};move(objects.t1,-1,1.4,finish);move(objects.t2,1,1.4,finish);})],['Ortak nesneye eriş',()=>{event('T1 ve T2 aynı heap nesnesini görebilir.','Paylaşım','Synchronization gerekli');note('Daha çok thread; serial stage, locks, memory bandwidth veya storage darboğazını ortadan kaldırmaz. Bu model benchmark değildir.');}]]);},
 ()=>{floor();building('ACCEPTOR',-5,-2,2,2,1,colors.mint);building('WORKER 1',1,-2,2,2,1.2,colors.blue);building('WORKER 2',5,-2,2,2,1.2,colors.purple);pad('BOUNDED QUEUE · 3',-3,2.4,0xdce1fa);state={queue:[],jobs:0,stopped:false};event('Kuyruk kapasitesi 3. Worker’lar bağımsız iş alır.','2 worker','Kuyruk 0 / 3');note('Queue sahiplik devrini düzenler. Dolu kuyruk, shutdown ve waiting worker’ı uyandırma kuralları tasarıma aittir. Event-driven alternatifler de vardır.');actionButtons([['İstek ekle',()=>{if(state.stopped)return event('Sunucu kapalı; yeni istek kabul etmiyor.','Stopped','Önce deneyi sıfırla');if(state.queue.length===3)return event('Queue dolu: bu deney yeni isteği reddediyor.','Workers','Backpressure policy');const q=token(-4+state.queue.length*.7,2.4);state.queue.push(q);event('İstek kuyruğa alındı.','Workers',`Queue ${state.queue.length} / 3`);}],['Worker’a ata',()=>{if(!state.queue.length)return event('Queue boş; worker iş bekleyebilir.','Idle','Queue 0 / 3');const q=state.queue.shift();lock(done=>move(q,state.jobs++%2?5:1,-.3,()=>{q.visible=false;event('İş worker tarafından tamamlandı; sahiplik bırakıldı.','Worker',`Queue ${state.queue.length} / 3`);done();}));}],['Shutdown',()=>{state.stopped=true;state.queue.forEach(q=>q.visible=false);state.queue=[];event('Bekleyen worker’lar uyandırıldı; bu örnekte kuyruk iptal edildi.','Stopped','Kaynaklar bırakıldı');}]]);},
 ()=>{floor();building('THREAD A',-4,-2,2.5,2,1.3,colors.blue);building('THREAD B',4,-2,2.5,2,1.3,colors.pink);objects.counter=rack('COUNTER',0,1,0,colors.purple);objects.a=token(-4,1);objects.b=token(4,1,colors.pink);state={value:0,step:0};const sequence=[['A read(0)',()=>move(objects.a,0,1)],['B read(0)',()=>move(objects.b,0,1)],['A write(1)',()=>{state.value=1;labelChange(objects.counter,'counter',0,1,'counter = 1');}],['B write(1)',()=>{labelChange(objects.counter,'counter',0,1,'counter = 1');}]];event('counter=0. İki increment beklenen sonuç: 2.','A + B','Shared counter');note('Bu, kavramsal lost-update trace’idir. Unsynchronized C conflicting access undefined behavior olabilir; gerçek program için “1 olur” garantisi yoktur.');actionButtons([['Race: sonraki işlem',()=>{if(state.step===4)return event(state.value===2?'Lock korumasında sonuç 2. Yeni race için deneyi sıfırla.':'İki increment, sonuç 1: bir güncelleme kayboldu.','A + B','Lost update');const [label,fn]=sequence[state.step++];fn();event(label+(state.step===4?' → Sonuç 1, beklenen 2.':''),'Interleaving','counter = '+state.value);}],['Lock ile iki increment',()=>{state.step=4;state.value=2;labelChange(objects.counter,'counter',0,1,'counter = 2');box(world,0,0,1,3,.12,2.8,colors.mint);event('A tüm increment’ı bitirdi; sonra B. Sonuç 2.','Mutual exclusion','Lock / atomic');}],['pthread_join örneği',()=>{labelChange(objects.counter,'result',0,1,'result = 49');event('main input=7 → worker result=49 → main join sonrası okur.','Worker tamamlandı','Nesne ömrü korunuyor');note('join sıralama sağlar; aynı anda çalışan diğer worker’ların ortak counter erişimini korumaz.');}]]);},
 ()=>{floor();building('printf',-5,-2,2.3,2,1.1,colors.blue);building('wc -l',5,-2,2.3,2,1.1,colors.mint);box(world,0,0,2.4,8,.13,1.4,0xcbd4e9);state={data:[],count:0,sent:false};text(world,'BYTE STREAM · MESAJ SINIRI YOK',0,1.6,2.4,.55);event('printf üretir; wc -l newline sayar.','Producer / consumer','Pipe buffer');note('Shell bağlantıyı kurar; printf builtin olabilir. read parçaları write parçalarına eşit olmak zorunda değildir. Message framing için delimiter/length gibi protokol gerekir.');actionButtons([['alpha\\nbeta\\n gönder',()=>{if(state.sent)return event('Bu akış tamamlandı; tekrar göndermek için deneyi sıfırla.','printf','Tek örnek akış');state.sent=true;['alpha','\\n','beta','\\n'].forEach((v,i)=>{const t=token(-3+i*1.1,2.4,v==='\\n'?colors.mint:colors.orange);const label=text(world,v,-3+i*1.1,1,2.4,.3);state.data.push({t,v,label});});event('Byte stream buffer’da; iki newline var.','printf','4 görsel parça · 11 byte');}],['Bir parça oku',()=>{if(!state.data.length)return event('Buffer boş. Writer açıkken read bekleyebilir.','wc waiting','EOF ayrı koşul');const {t,v,label}=state.data.shift();label.visible=false;if(v==='\\n')state.count++;lock(done=>move(t,5,2.4,()=>{t.visible=false;event(`Okunan parça: ${v}. Newline sayısı = ${state.count}.`,'wc -l','Buffer '+state.data.length);done();}));}],['Shared memory ile karşılaştır',()=>select('IPC protokolü','Shared memory ortak alan verir; message passing veri aktarır. İkisi de anlam, sıra, ownership, synchronization ve gönderici hatası kuralları ister.')]]);},
 ()=>{floor();building('WRITER',-5,-2,2.3,2,1.2,colors.blue);building('READER',5,-2,2.3,2,1.2,colors.mint);pad('BUFFER · 3 SLOT',0,2.4,0xdbe1f0);objects.child=box(world,-2.7,.1,2.4,.16,.7,1.2,colors.mint);objects.parent=box(world,2.7,.1,2.4,.16,.7,1.2,colors.orange);text(world,'CHILD FD',-2.7,1.4,2.4,.32);text(world,'PARENT FD',2.7,1.4,2.4,.32);state={buffer:[],child:true,parent:true};event('İki write-end referansı açık. Buffer boş.','Reader bekleyebilir','Writers = 2');note('Boş buffer EOF demek değildir. EOF: tüm writer referansları kapalı ve buffer tüketilmiş. Dolu buffer blocking writer’ı space beklemeye alabilir.');const report=()=>{const w=Number(state.child)+Number(state.parent);event(!w&&!state.buffer.length?'read → EOF':!state.buffer.length?'Buffer boş; writer hâlâ açık → read bekler.':state.buffer.length===3?'Buffer dolu → blocking writer space bekler.':'Buffer’da veri var.','Writer / reader',`Writers ${w} · buffer ${state.buffer.length}/3`);};actionButtons([['Buffer’a yaz',()=>{if(!state.child&&!state.parent)return report();if(state.buffer.length<3)state.buffer.push(token(-.8+state.buffer.length*.8,2.4));report();}],['Buffer’dan oku',()=>{state.buffer.shift()?.removeFromParent();report();}],['Child write-end kapat',()=>{state.child=false;objects.child.visible=false;report();}],['Parent write-end kapat',()=>{state.parent=false;objects.parent.visible=false;report();}]]);},
 ()=>{floor();cpu();objects.p=bot('P',-5,2.4);rack('MEMORY',-4,-2,10);building('PIPE',4,-2,2.5,2,1,colors.mint);state={checkpoint:0};event('Beş soruda bir programın ömrünü takip et.','Model','Kimlik · durum · paylaşım');note('Pratik: background process gözlemle, launch/thread örneklerini derle; önce sonucu tahmin et. Burada graded deadline yok.');const questions=[['Kimlik','fork yeni process; exec aynı PID, yeni image.'],['Durum','Ready CPU bekler; waiting eksik olayı bekler.'],['Yürütme','Kernel entry ve task switch ayrı olaylar.'],['Paylaşım','Process alanları ayrı; thread adres alanı ortak.'],['Tamamlanma','Unused FD kapat; EOF gözle; join/wait ve cleanup yap.']];actionButtons([['Sonraki kontrol',()=>{const [q,a]=questions[state.checkpoint++%5];event(a,q,'Kontrol '+state.checkpoint);note(q+': '+a);}],['Kaynakları aç',()=>select('Okuma rotası','OSC 10e Chapters 1–4; fork(2), execve(2), waitpid(2), pipe(7). OSTEP processes/process API/threads bölümleri. Özgün reading ek kaynakları içerir.')]]);}
 ];
 function select(name,desc){dirty=true;$('.selection-card').hidden=false;$('.selection-card strong').textContent=name;$('.selection-card p').textContent=desc;}
 function load(index){current=index;state={};const c=chapters[index];$('#mission-number').textContent='KEŞİF '+String(index+1).padStart(2,'0');$('#mission-title').textContent=c.title;$('#mission-description').textContent=c.intro;$('#experiment-name').textContent=c.title;$('#notes-link').href='#konu-'+(index+1);root.querySelectorAll('.mission').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));$('.selection-card').hidden=true;if(renderer){cleanup();scenes[index]();}else{event(c.intro,'Metin modu','3B kullanılamıyor');note(c.notes[0]);actionButtons([['Konuyu oku',()=>document.querySelector('#konu-'+(index+1)).scrollIntoView({behavior:'smooth'})]]);}}
 root.querySelectorAll('.mission').forEach(b=>b.onclick=()=>load(Number(b.dataset.mission)));
 document.querySelectorAll('[data-open-mission]').forEach(b=>b.onclick=()=>{load(Number(b.dataset.openMission));root.scrollIntoView({behavior:reduced.matches?'instant':'smooth'});});
 $('.close-selection').onclick=()=>$('.selection-card').hidden=true;
 $('.camera-reset').onclick=()=>{camera?.position.set(15,15,18);controls?.target.set(0,0,0);};$('.zoom-in').onclick=()=>{if(camera)camera.position.multiplyScalar(.9);};$('.zoom-out').onclick=()=>{if(camera)camera.position.multiplyScalar(1.1);};
 if(renderer){let down;canvas.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=canvas.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(pickables).find(h=>h.object.visible&&h.object.userData.owner.visible);if(hit){const {name,desc}=hit.object.userData.owner.userData;select(name,desc);}});}
 load(0);
}
